### ISSUE TITLE
Ran pod install, but getting HexColor.h file not found

### ISSUE THREAD

**Issue by bennettl** [Loadex/MessageBanner#11] opened 2015-07-07 17:16 UTC
As instructed, I used Cocopods to install the message banner with 

 pod 'MessageBanner', '~> 1.0'

But I received an error:

![screen shot 2015-07-07 at 10 15 38 am](https://cloud.githubusercontent.com/assets/1672224/8552308/26570c84-2491-11e5-9c46-f2d5801bfa03.png)

I also tried adding 

pod 'HexColors', '~> 2.3'
pod 'FXBlurView', '~> 1.6'

But still getting the same error

**Comment by plaetzchen** [comment] 2015-07-08 08:43
The problem is, that HexColors changed there header file name to HexColors.h (from HexColor.h) so this change is needed in MessageBanner. You can fix this by adding pod 'HexColors', '2.2.1' to your Podfile. 
I will make a Pull Request.

**Comment by Loadex** [comment] 2015-07-08 08:45
@bennettl  Thanks for opening the issue !
And thanks @plaetzchen for the answer, I will be waiting to accept your pull request ! :wink:

**Comment by plaetzchen** [comment] 2015-07-08 09:11
@Loadex Will you do a pull request to CocoaPods?

**Comment by Loadex** [comment] 2015-07-08 09:12
@plaetzchen Updating the pod version right now !

**Comment by Loadex** [comment] 2015-07-08 09:16
` - Log messages:
    - July 8th, 10:15: Push for `MessageBanner 1.0.4' initiated.
    - July 8th, 10:15: Push for `MessageBanner 1.0.4' has been pushed (1.554057242 s).`

**Comment by Loadex** [comment] 2015-07-08 09:18
If you already have MessageBanner installed in your podfile.lock, you must run `pod update MessageBanner` to access the new version.

**Comment by Loadex** [comment] 2015-07-08 09:22
I keep the issue open for a few minute. If you have any problem updating, please let me know here.

**Comment by plaetzchen** [comment] 2015-07-08 09:40
Of course you will need to remove the explicit HexColors dependency first.

**Comment by plaetzchen** [comment] 2015-07-08 09:42
Works for me.

**Comment by Loadex** [comment] 2015-07-08 09:56
Thanks @plaetzchen.
Closing the issue.

**Closed by Loadex** 2015-07-08 09:56 UTC
